version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/calander-front
    overwrite: yes
permissions:
  - object: /home/ubuntu/calander-front
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 300
      runas: ubuntu
