name: Deploy

on:
  push:
    branches: ["develop"]

jobs:
  build:
    runs-on: ubuntu-latest

    container: pandoc/latex

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2

      - name: Install mustache (to update the date)
        run: sudo apt-get update && sudo apt-get install -y ruby-full && gem install mustache

      - name: Run build script
        run: chmod +x ./build.sh && sh ./build.sh

      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.AUTO_ACTIONS }}
        with:
          source-directory: "output"
          destination-github-username: wo-o29
          destination-repository-name: calander-front-fork
          user-email: ${{ secrets.EMAIL }}
          commit-message: ${{ github.event.commits[0].message }}
          target-branch: develop

      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
